name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
      persist-credentials: 'false'
      node-version: '16'
      
    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Run Prettier
      run: npm run prettier

    - name: Run tests
      env:
        CI: true
      run: npm run test

    - name: Build
      run: npm run build
