name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.CICD }}
        name: id_rsa # optional
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        
    -   run: |
            git clone git@github.com:TopeAU/CI-CD.git

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.0.1'


    - name: Install dependencies
      working-directory: /home/runner/work/CI-CD/CI-CD/codebase/rdicidr-0.1.0/
      run: npm install

    - name: Lint code
      working-directory: /home/runner/work/CI-CD/CI-CD/codebase/rdicidr-0.1.0/
      run: npm run lint

    - name: Run tests
      working-directory: /home/runner/work/CI-CD/CI-CD/codebase/rdicidr-0.1.0/
      env:
        CI: true
      run: npm run test

    - name: Build
      run: npm run build
